# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/host/usr/bin/cmake

# The command to remove a file.
RM = /home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/host/usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/build/libcutils-2c61c38

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/build/libcutils-2c61c38

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/host/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@echo "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@echo "Install the project..."
	/home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/host/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@echo "Install the project..."
	/home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/host/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@echo "Installing only the local directory..."
	/home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/host/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@echo "No interactive CMake dialog available..."
	/home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/host/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/build/libcutils-2c61c38/CMakeFiles /home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/build/libcutils-2c61c38/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhk/work/work/rk3399/rk3399_linux/buildroot/output/build/libcutils-2c61c38/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cutils

# Build rule for target.
cutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cutils
.PHONY : cutils

# fast build rule for target.
cutils/fast:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/build
.PHONY : cutils/fast

# target to build an object file
arch-arm64/android_memset.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/arch-arm64/android_memset.o
.PHONY : arch-arm64/android_memset.o

# target to build an object file
ashmem-dev.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/ashmem-dev.o
.PHONY : ashmem-dev.o

# target to preprocess a source file
ashmem-dev.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/ashmem-dev.i
.PHONY : ashmem-dev.i

# target to generate assembly for a file
ashmem-dev.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/ashmem-dev.s
.PHONY : ashmem-dev.s

# target to build an object file
atomic.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/atomic.o
.PHONY : atomic.o

# target to preprocess a source file
atomic.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/atomic.i
.PHONY : atomic.i

# target to generate assembly for a file
atomic.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/atomic.s
.PHONY : atomic.s

# target to build an object file
config_utils.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/config_utils.o
.PHONY : config_utils.o

# target to preprocess a source file
config_utils.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/config_utils.i
.PHONY : config_utils.i

# target to generate assembly for a file
config_utils.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/config_utils.s
.PHONY : config_utils.s

# target to build an object file
debugger.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/debugger.o
.PHONY : debugger.o

# target to preprocess a source file
debugger.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/debugger.i
.PHONY : debugger.i

# target to generate assembly for a file
debugger.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/debugger.s
.PHONY : debugger.s

# target to build an object file
fs_config.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/fs_config.o
.PHONY : fs_config.o

# target to preprocess a source file
fs_config.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/fs_config.i
.PHONY : fs_config.i

# target to generate assembly for a file
fs_config.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/fs_config.s
.PHONY : fs_config.s

# target to build an object file
hashmap.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/hashmap.o
.PHONY : hashmap.o

# target to preprocess a source file
hashmap.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/hashmap.i
.PHONY : hashmap.i

# target to generate assembly for a file
hashmap.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/hashmap.s
.PHONY : hashmap.s

# target to build an object file
iosched_policy.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/iosched_policy.o
.PHONY : iosched_policy.o

# target to preprocess a source file
iosched_policy.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/iosched_policy.i
.PHONY : iosched_policy.i

# target to generate assembly for a file
iosched_policy.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/iosched_policy.s
.PHONY : iosched_policy.s

# target to build an object file
klog.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/klog.o
.PHONY : klog.o

# target to preprocess a source file
klog.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/klog.i
.PHONY : klog.i

# target to generate assembly for a file
klog.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/klog.s
.PHONY : klog.s

# target to build an object file
load_file.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/load_file.o
.PHONY : load_file.o

# target to preprocess a source file
load_file.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/load_file.i
.PHONY : load_file.i

# target to generate assembly for a file
load_file.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/load_file.s
.PHONY : load_file.s

# target to build an object file
native_handle.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/native_handle.o
.PHONY : native_handle.o

# target to preprocess a source file
native_handle.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/native_handle.i
.PHONY : native_handle.i

# target to generate assembly for a file
native_handle.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/native_handle.s
.PHONY : native_handle.s

# target to build an object file
open_memstream.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/open_memstream.o
.PHONY : open_memstream.o

# target to preprocess a source file
open_memstream.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/open_memstream.i
.PHONY : open_memstream.i

# target to generate assembly for a file
open_memstream.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/open_memstream.s
.PHONY : open_memstream.s

# target to build an object file
partition_utils.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/partition_utils.o
.PHONY : partition_utils.o

# target to preprocess a source file
partition_utils.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/partition_utils.i
.PHONY : partition_utils.i

# target to generate assembly for a file
partition_utils.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/partition_utils.s
.PHONY : partition_utils.s

# target to build an object file
process_name.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/process_name.o
.PHONY : process_name.o

# target to preprocess a source file
process_name.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/process_name.i
.PHONY : process_name.i

# target to generate assembly for a file
process_name.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/process_name.s
.PHONY : process_name.s

# target to build an object file
properties.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/properties.o
.PHONY : properties.o

# target to preprocess a source file
properties.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/properties.i
.PHONY : properties.i

# target to generate assembly for a file
properties.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/properties.s
.PHONY : properties.s

# target to build an object file
qtaguid.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/qtaguid.o
.PHONY : qtaguid.o

# target to preprocess a source file
qtaguid.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/qtaguid.i
.PHONY : qtaguid.i

# target to generate assembly for a file
qtaguid.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/qtaguid.s
.PHONY : qtaguid.s

# target to build an object file
record_stream.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/record_stream.o
.PHONY : record_stream.o

# target to preprocess a source file
record_stream.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/record_stream.i
.PHONY : record_stream.i

# target to generate assembly for a file
record_stream.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/record_stream.s
.PHONY : record_stream.s

# target to build an object file
sched_policy.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/sched_policy.o
.PHONY : sched_policy.o

# target to preprocess a source file
sched_policy.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/sched_policy.i
.PHONY : sched_policy.i

# target to generate assembly for a file
sched_policy.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/sched_policy.s
.PHONY : sched_policy.s

# target to build an object file
socket_inaddr_any_server.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_inaddr_any_server.o
.PHONY : socket_inaddr_any_server.o

# target to preprocess a source file
socket_inaddr_any_server.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_inaddr_any_server.i
.PHONY : socket_inaddr_any_server.i

# target to generate assembly for a file
socket_inaddr_any_server.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_inaddr_any_server.s
.PHONY : socket_inaddr_any_server.s

# target to build an object file
socket_local_client.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_local_client.o
.PHONY : socket_local_client.o

# target to preprocess a source file
socket_local_client.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_local_client.i
.PHONY : socket_local_client.i

# target to generate assembly for a file
socket_local_client.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_local_client.s
.PHONY : socket_local_client.s

# target to build an object file
socket_local_server.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_local_server.o
.PHONY : socket_local_server.o

# target to preprocess a source file
socket_local_server.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_local_server.i
.PHONY : socket_local_server.i

# target to generate assembly for a file
socket_local_server.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_local_server.s
.PHONY : socket_local_server.s

# target to build an object file
socket_loopback_client.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_loopback_client.o
.PHONY : socket_loopback_client.o

# target to preprocess a source file
socket_loopback_client.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_loopback_client.i
.PHONY : socket_loopback_client.i

# target to generate assembly for a file
socket_loopback_client.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_loopback_client.s
.PHONY : socket_loopback_client.s

# target to build an object file
socket_loopback_server.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_loopback_server.o
.PHONY : socket_loopback_server.o

# target to preprocess a source file
socket_loopback_server.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_loopback_server.i
.PHONY : socket_loopback_server.i

# target to generate assembly for a file
socket_loopback_server.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_loopback_server.s
.PHONY : socket_loopback_server.s

# target to build an object file
socket_network_client.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_network_client.o
.PHONY : socket_network_client.o

# target to preprocess a source file
socket_network_client.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_network_client.i
.PHONY : socket_network_client.i

# target to generate assembly for a file
socket_network_client.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/socket_network_client.s
.PHONY : socket_network_client.s

# target to build an object file
sockets.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/sockets.o
.PHONY : sockets.o

# target to preprocess a source file
sockets.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/sockets.i
.PHONY : sockets.i

# target to generate assembly for a file
sockets.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/sockets.s
.PHONY : sockets.s

# target to build an object file
str_parms.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/str_parms.o
.PHONY : str_parms.o

# target to preprocess a source file
str_parms.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/str_parms.i
.PHONY : str_parms.i

# target to generate assembly for a file
str_parms.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/str_parms.s
.PHONY : str_parms.s

# target to build an object file
strdup16to8.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/strdup16to8.o
.PHONY : strdup16to8.o

# target to preprocess a source file
strdup16to8.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/strdup16to8.i
.PHONY : strdup16to8.i

# target to generate assembly for a file
strdup16to8.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/strdup16to8.s
.PHONY : strdup16to8.s

# target to build an object file
strdup8to16.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/strdup8to16.o
.PHONY : strdup8to16.o

# target to preprocess a source file
strdup8to16.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/strdup8to16.i
.PHONY : strdup8to16.i

# target to generate assembly for a file
strdup8to16.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/strdup8to16.s
.PHONY : strdup8to16.s

# target to build an object file
strlcpy.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/strlcpy.o
.PHONY : strlcpy.o

# target to preprocess a source file
strlcpy.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/strlcpy.i
.PHONY : strlcpy.i

# target to generate assembly for a file
strlcpy.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/strlcpy.s
.PHONY : strlcpy.s

# target to build an object file
threads.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/threads.o
.PHONY : threads.o

# target to preprocess a source file
threads.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/threads.i
.PHONY : threads.i

# target to generate assembly for a file
threads.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/threads.s
.PHONY : threads.s

# target to build an object file
trace-dev.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/trace-dev.o
.PHONY : trace-dev.o

# target to preprocess a source file
trace-dev.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/trace-dev.i
.PHONY : trace-dev.i

# target to generate assembly for a file
trace-dev.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/trace-dev.s
.PHONY : trace-dev.s

# target to build an object file
uevent.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/uevent.o
.PHONY : uevent.o

# target to preprocess a source file
uevent.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/uevent.i
.PHONY : uevent.i

# target to generate assembly for a file
uevent.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/uevent.s
.PHONY : uevent.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... cutils"
	@echo "... arch-arm64/android_memset.o"
	@echo "... ashmem-dev.o"
	@echo "... ashmem-dev.i"
	@echo "... ashmem-dev.s"
	@echo "... atomic.o"
	@echo "... atomic.i"
	@echo "... atomic.s"
	@echo "... config_utils.o"
	@echo "... config_utils.i"
	@echo "... config_utils.s"
	@echo "... debugger.o"
	@echo "... debugger.i"
	@echo "... debugger.s"
	@echo "... fs_config.o"
	@echo "... fs_config.i"
	@echo "... fs_config.s"
	@echo "... hashmap.o"
	@echo "... hashmap.i"
	@echo "... hashmap.s"
	@echo "... iosched_policy.o"
	@echo "... iosched_policy.i"
	@echo "... iosched_policy.s"
	@echo "... klog.o"
	@echo "... klog.i"
	@echo "... klog.s"
	@echo "... load_file.o"
	@echo "... load_file.i"
	@echo "... load_file.s"
	@echo "... native_handle.o"
	@echo "... native_handle.i"
	@echo "... native_handle.s"
	@echo "... open_memstream.o"
	@echo "... open_memstream.i"
	@echo "... open_memstream.s"
	@echo "... partition_utils.o"
	@echo "... partition_utils.i"
	@echo "... partition_utils.s"
	@echo "... process_name.o"
	@echo "... process_name.i"
	@echo "... process_name.s"
	@echo "... properties.o"
	@echo "... properties.i"
	@echo "... properties.s"
	@echo "... qtaguid.o"
	@echo "... qtaguid.i"
	@echo "... qtaguid.s"
	@echo "... record_stream.o"
	@echo "... record_stream.i"
	@echo "... record_stream.s"
	@echo "... sched_policy.o"
	@echo "... sched_policy.i"
	@echo "... sched_policy.s"
	@echo "... socket_inaddr_any_server.o"
	@echo "... socket_inaddr_any_server.i"
	@echo "... socket_inaddr_any_server.s"
	@echo "... socket_local_client.o"
	@echo "... socket_local_client.i"
	@echo "... socket_local_client.s"
	@echo "... socket_local_server.o"
	@echo "... socket_local_server.i"
	@echo "... socket_local_server.s"
	@echo "... socket_loopback_client.o"
	@echo "... socket_loopback_client.i"
	@echo "... socket_loopback_client.s"
	@echo "... socket_loopback_server.o"
	@echo "... socket_loopback_server.i"
	@echo "... socket_loopback_server.s"
	@echo "... socket_network_client.o"
	@echo "... socket_network_client.i"
	@echo "... socket_network_client.s"
	@echo "... sockets.o"
	@echo "... sockets.i"
	@echo "... sockets.s"
	@echo "... str_parms.o"
	@echo "... str_parms.i"
	@echo "... str_parms.s"
	@echo "... strdup16to8.o"
	@echo "... strdup16to8.i"
	@echo "... strdup16to8.s"
	@echo "... strdup8to16.o"
	@echo "... strdup8to16.i"
	@echo "... strdup8to16.s"
	@echo "... strlcpy.o"
	@echo "... strlcpy.i"
	@echo "... strlcpy.s"
	@echo "... threads.o"
	@echo "... threads.i"
	@echo "... threads.s"
	@echo "... trace-dev.o"
	@echo "... trace-dev.i"
	@echo "... trace-dev.s"
	@echo "... uevent.o"
	@echo "... uevent.i"
	@echo "... uevent.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

